import 'package:cloud_firestore/cloud_firestore.dart';

enum SessionType {
  regular,
  cover,
  makeup,
  extra,
  cancelled,
  cancelledCenter,
  cancelledClient,
  completed,
}

class ServiceDetail {
  final String type;
  final String startTime;
  final String endTime;
  final String employeeId;
  final bool isInclusive;

  ServiceDetail({
    required this.type,
    required this.startTime,
    required this.endTime,
    required this.employeeId,
    this.isInclusive = false,
  });

  Map<String, dynamic> toJson() => {
    'type': type,
    'startTime': startTime,
    'endTime': endTime,
    'employeeId': employeeId,
    'isInclusive': isInclusive,
  };

  factory ServiceDetail.fromJson(Map<String, dynamic> json) => ServiceDetail(
    type: json['type'] as String? ?? 'ABA',
    startTime: json['startTime'] as String? ?? '',
    endTime: json['endTime'] as String? ?? '',
    employeeId: json['employeeId'] as String? ?? '',
    isInclusive: json['isInclusive'] as bool? ?? false,
  );

  ServiceDetail copyWith({
    String? type,
    String? startTime,
    String? endTime,
    String? employeeId,
    bool? isInclusive,
  }) {
    return ServiceDetail(
      type: type ?? this.type,
      startTime: startTime ?? this.startTime,
      endTime: endTime ?? this.endTime,
      employeeId: employeeId ?? this.employeeId,
      isInclusive: isInclusive ?? this.isInclusive,
    );
  }

  double get duration {
    if (startTime.isEmpty || endTime.isEmpty) return 0.0;
    try {
      final start = DateTime.parse('2024-01-01 $startTime:00');
      final end = DateTime.parse('2024-01-01 $endTime:00');
      return end.difference(start).inMinutes / 60.0;
    } catch (_) {
      return 0.0;
    }
  }

  @override
  String toString() => '$startTime-$endTime $type';
}

class Session {
  final String id;
  final String clientId;
  final String timeSlotId;
  final Timestamp date;
  final SessionType sessionType;
  final List<ServiceDetail> services;
  final String? notes;
  final bool isAutoGenerated;
  final Timestamp createdAt;

  Session({
    required this.id,
    required this.clientId,
    required this.timeSlotId,
    required this.date,
    required this.sessionType,
    required this.services,
    this.notes,
    this.isAutoGenerated = false,
    required this.createdAt,
  });

  double get totalDuration =>
      services.fold(0.0, (sum, item) => sum + item.duration);

  String get servicesDisplay =>
      '[${services.map((s) => s.toString()).join(', ')}]';

  Map<String, dynamic> toJson() {
    return {
      'clientId': clientId,
      'timeSlotId': timeSlotId,
      'date': date,
      'sessionType': sessionType.name,
      'services': services.map((s) => s.toJson()).toList(),
      'notes': notes,
      'isAutoGenerated': isAutoGenerated,
      'createdAt': createdAt,
    };
  }

  factory Session.fromFirestore(
    DocumentSnapshot<Map<String, dynamic>> snapshot,
  ) {
    final data = snapshot.data()!;
    return Session(
      id: snapshot.id,
      clientId: data['clientId'] as String? ?? '',
      timeSlotId: data['timeSlotId'] as String? ?? '',
      date: (data['date'] as Timestamp?) ?? Timestamp.now(),
      sessionType: SessionType.values.byName(
        data['sessionType'] as String? ?? 'regular',
      ),
      services:
          (data['services'] as List<dynamic>?)
              ?.map((s) => ServiceDetail.fromJson(s as Map<String, dynamic>))
              .toList() ??
          [],
      notes: data['notes'] as String?,
      isAutoGenerated: data['isAutoGenerated'] as bool? ?? false,
      createdAt: (data['createdAt'] as Timestamp?) ?? Timestamp.now(),
    );
  }

  Session copyWith({
    String? id,
    String? clientId,
    String? employeeId,
    String? timeSlotId,
    Timestamp? date,
    SessionType? sessionType,
    List<ServiceDetail>? services,
    String? notes,
    bool? isAutoGenerated,
    Timestamp? createdAt,
  }) {
    return Session(
      id: id ?? this.id,
      clientId: clientId ?? this.clientId,
      timeSlotId: timeSlotId ?? this.timeSlotId,
      date: date ?? this.date,
      sessionType: sessionType ?? this.sessionType,
      services: services ?? this.services,
      notes: notes ?? this.notes,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}
